### ISSUE TITLE
ExceptionInitializer & NoClassDefFound error testing Shared-Library example

### ISSUE THREAD

**Issue by dovishly** [ExpediaGroup/jenkins-spock#108]
Hi, I'm attempting to test the Shared-Library example provided in this repository to get a feel for Jenkins-Spock and hopefully use it in a shared-library I'm helping to develop.

Problem is, when I try to `mvn clean test`, I get an ExceptionInitializer error for one test, and a NoClassDefFound error for the other (stack trace attached at the bottom)

While I am familiar with Java, I am relatively new to Groovy, Jenkins, Spock, and shared libraries.

The only changes I made to the pom.xml was because it was complaining about being too low of a version without it:
```	
<maven.compiler.source>1.8</maven.compiler.source>
<maven.compiler.target>1.8</maven.compiler.target>
```

Perhaps I missed a required step? Or is this example only for viewing purposes?

Thank you for your time.

```[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running DefaultPipelineSpec
Sep 10, 2021 8:37:17 AM jenkins.model.Jenkins <clinit>
SEVERE: Failed to load Jenkins.class
java.lang.ExceptionInInitializerError
        at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:811)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:350)
        at hudson.util.XStream2.<init>(XStream2.java:100)
        at jenkins.model.Jenkins.<clinit>(Jenkins.java:5091)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
        at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42)
        at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
        at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1126)
        at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1107)
        at java.base/java.lang.reflect.Field.set(Field.java:793)
        at org.codehaus.groovy.reflection.CachedField.setProperty(CachedField.java:74)
        at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2689)
        at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3770)
        at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:199)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setProperty(ScriptBytecodeAdapter.java:484)
        at com.homeaway.devtools.jenkins.testing.JenkinsPipelineSpecification.setupSpec(JenkinsPipelineSpecification.groovy:1101)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:188)
        at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:84)
        at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:481)
        at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:464)
        at org.spockframework.runtime.BaseSpecRunner.doRunSetupSpec(BaseSpecRunner.java:180)
        at org.spockframework.runtime.BaseSpecRunner$3.invoke(BaseSpecRunner.java:164)
        at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:481)
        at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:464)
        at org.spockframework.runtime.BaseSpecRunner.runSetupSpec(BaseSpecRunner.java:157)
        at org.spockframework.runtime.BaseSpecRunner.doRunSetupSpec(BaseSpecRunner.java:177)
        at org.spockframework.runtime.BaseSpecRunner$3.invoke(BaseSpecRunner.java:164)
        at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:481)
        at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:464)
        at org.spockframework.runtime.BaseSpecRunner.runSetupSpec(BaseSpecRunner.java:157)
        at org.spockframework.runtime.BaseSpecRunner.runSetupSpec(BaseSpecRunner.java:152)
        at org.spockframework.runtime.BaseSpecRunner.doRunSpec(BaseSpecRunner.java:97)
        at org.spockframework.runtime.BaseSpecRunner$1.invoke(BaseSpecRunner.java:84)
        at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:481)
        at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:464)
        at org.spockframework.runtime.BaseSpecRunner.runSpec(BaseSpecRunner.java:76)
        at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:67)
        at org.spockframework.runtime.Sputnik.run(Sputnik.java:63)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @31ef45e3
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
        at com.thoughtworks.xstream.core.util.Fields.locate(Fields.java:39)
        at com.thoughtworks.xstream.converters.collections.TreeMapConverter.<clinit>(TreeMapConverter.java:50)
        ... 55 more

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.445 s <<< FAILURE! - in DefaultPipelineSpec
[ERROR] DefaultPipelineSpec  Time elapsed: 1.439 s  <<< ERROR!
java.lang.ExceptionInInitializerError
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @31ef45e3

[INFO] Running DeployerSpec
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in DeployerSpec
[ERROR] DeployerSpec  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   DefaultPipelineSpec>JenkinsPipelineSpecification.setupSpec:1101 ▒ ExceptionInInitializer
[ERROR]   DeployerSpec>JenkinsPipelineSpecification.setupSpec:1101 ▒ NoClassDefFound Cou...
[INFO]
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.032 s
[INFO] Finished at: 2021-09-10T08:37:18-04:00
[INFO] ------------------------------------------------------------------------```

**Comment by deblaci** [comment]
Hi,

Setup java home to jdk11 and use groovy 2.4.x
Check the java version with mvn version .

**Comment by dovishly** [comment]
Yes, this was a java 16 issue. I set up java 8 instead and it worked. Thanks!
