### ISSUE TITLE
NullPointerException when chaining methods of mocked step

### ISSUE THREAD

**Issue by ChriFo** [ExpediaGroup/jenkins-spock#14]
Expected Behavior
==============================

The following line of a custom pipeline step should be mockable and produce an invocation on the mock object.

`docker.image("node").inside("-u root") { sh "node -v" }`

Actual Behavior
==============================

But instead of an invocation on the mock object the following exception occurred:

```
java.lang.NullPointerException: Cannot invoke method inside() on null object
        at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
        at withDockerNode.call(withDockerNode.groovy:16)
        at withDockerNode.call(withDockerNode.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
        at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:947)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:930)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:181)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeClosure(ScriptBytecodeAdapter.java:587)
        at WithDockerNodeSpec.$spock_feature_1_1(WithDockerNodeSpec.groovy:26)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:200)
        at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:113)
        at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:484)
        at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467)
        at org.spockframework.runtime.BaseSpecRunner.runFeatureMethod(BaseSpecRunner.java:408)
        at org.spockframework.runtime.BaseSpecRunner.doRunIteration(BaseSpecRunner.java:322)
        at org.spockframework.runtime.BaseSpecRunner$6.invoke(BaseSpecRunner.java:306)
        at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:484)
        at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467)
        at org.spockframework.runtime.BaseSpecRunner.runIteration(BaseSpecRunner.java:285)
        at org.spockframework.runtime.BaseSpecRunner.initializeAndRunIteration(BaseSpecRunner.java:275)
        at org.spockframework.runtime.BaseSpecRunner.runSimpleFeature(BaseSpecRunner.java:266)
        at org.spockframework.runtime.BaseSpecRunner.doRunFeature(BaseSpecRunner.java:260)
        at org.spockframework.runtime.BaseSpecRunner$5.invoke(BaseSpecRunner.java:243)
        at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:484)
        at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467)
        at org.spockframework.runtime.BaseSpecRunner.runFeature(BaseSpecRunner.java:235)
        at org.spockframework.runtime.BaseSpecRunner.runFeatures(BaseSpecRunner.java:185)
        at org.spockframework.runtime.BaseSpecRunner.doRunSpec(BaseSpecRunner.java:95)
        at org.spockframework.runtime.BaseSpecRunner$1.invoke(BaseSpecRunner.java:81)
        at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:484)
        at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467)
        at org.spockframework.runtime.BaseSpecRunner.runSpec(BaseSpecRunner.java:73)
        at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:64)
        at org.spockframework.runtime.Sputnik.run(Sputnik.java:63)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
```

Additional Information
==============================

I added the following dependency to get the docker step sources
```
<dependency>
  <!-- provides docker() step -->
  <groupId>org.jenkins-ci.plugins</groupId>
  <artifactId>docker-workflow</artifactId>
  <version>LATEST</version>
  <scope>test</scope>
</dependency>
```

**java -version**
```
java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```

**Comment by awittha** [comment]
The steps _are_ mocked - but mocks return `null` unless an interaction is stubbed. You'll need to explicitly stub each method that is a part of the chain.

This uncertain territory because the `docker.image(...)` method returns an instance of the [Image class defined in the `Docker.groovy` script](https://github.com/jenkinsci/docker-workflow-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy#L102) - it isn't a compiled Groovy or Java class. `loadPipelineScriptForTest(...)` doesn't support loading scripts that are from outside your project, either, so you can't use `loadPipelineScriptForTest("org/jenkinsci/plugins/docker/workflow/Docker.groovy")`

If you don't need actual typing, you can use `explicitlyMockPipelineVariable` to stand in for the `Image` object that `docker` would create. This is probably fine...

`Jenkinsfile`:
```groovy
docker.image("node").inside("-u root") { sh "node -v" }
```

`JenkinsfileSpec.groovy`:
```groovy
def Jenkinsfile = null

def setup() {
	Jenkinsfile = loadPipelineScriptForTest("/Jenkinsfile")

	getPipelineMock("docker.image")("node") >> explicitlyMockPipelineVariable("NodeImage")
}

def "should work"() {
	when:
		Jenkinsfile.run()
	then:
		1 * getPipelineMock("sh")("node -v")
}
```

Just be careful that the name chosen for the mocked image (`NodeImage`) doesn't overlap with a real variable name used anywhere.

If you wanted to check interactions against that particular docker image, you could use

```groovy
then:
	1 * getPipelineMock("NodeImage.inside")("-u root", _ as Closure)
```

**Comment by ChriFo** [comment]
The global setup of the method stub did not work...
I ended with the following setup (simplified!).

**myStep.groovy**
```groovy
def call(map = [:], Closure body) {
	docker.image(map.tag).inside(map.args) {
		body()
	}
}
```
**MyStepSpec.groovy**
```groovy
def myStep = null

def setup() {
	myStep = loadPipelineScriptForTest("vars/myStep.groovy")
}

def "should work"() {
	when:
		myStep(tag: "node", args: "-u root") {
			echo "hello world"
		}
	then:
		1 * getPipelineMock("docker.image")("node") >> explicitlyMockPipelineVariable("Image")
		1 * getPipelineMock("Image.inside")("-u root", _ as Closure)
		1 * getPipelineMock("echo")("hello world")
}
```
Thank you very much. Thats what I call _teamwork_ :wink:
