### ISSUE TITLE
RuntimeException: Unknown constant pool tag 60 in classfile com/ibm/icu/impl/data/LocaleElements_zh__PINYIN.class

### ISSUE THREAD

**Issue by sebarre-talend** [ExpediaGroup/jenkins-spock#59]
Hey, i cannot test my project, which is currently very simple. Could you take a look at that ? Thanks ! 

Expected Behavior
==============================

The project builds

Actual Behavior
==============================

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unknown constant pool tag 60 in classfile com/ibm/icu/impl/data/LocaleElements_zh__PINYIN.class (element size unknown, cannot continue reading class. Please report this on the FastClasspathScanner GitHub page.
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1644)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1678)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1704)
	at com.homeaway.devtools.jenkins.testing.WholeClasspathPipelineExtensionDetector.getClassesWithAnnotationOfTypeInPackage(WholeClasspathPipelineExtensionDetector.java:97)
	at com.homeaway.devtools.jenkins.testing.APipelineExtensionDetector.getPipelineSteps(APipelineExtensionDetector.java:81)
	at com.homeaway.devtools.jenkins.testing.JenkinsPipelineSpecification.setupSpec(JenkinsPipelineSpecification.groovy:999)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unknown constant pool tag 60 in classfile com/ibm/icu/impl/data/LocaleElements_zh__PINYIN.class (element size unknown, cannot continue reading class. Please report this on the FastClasspathScanner GitHub page.
	at io.github.lukehutch.fastclasspathscanner.utils.InterruptionChecker.executionException(InterruptionChecker.java:86)
	at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue.runWorkLoop(WorkQueue.java:199)
	at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue$1.call(WorkQueue.java:147)
	at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue$1.call(WorkQueue.java:144)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.RuntimeException: Unknown constant pool tag 60 in classfile com/ibm/icu/impl/data/LocaleElements_zh__PINYIN.class (element size unknown, cannot continue reading class. Please report this on the FastClasspathScanner GitHub page.
	at io.github.lukehutch.fastclasspathscanner.scanner.ClassfileBinaryParser.readClassInfoFromClassfileHeader(ClassfileBinaryParser.java:646)
	at io.github.lukehutch.fastclasspathscanner.scanner.ClasspathElement.parseClassfiles(ClasspathElement.java:297)
	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner$6.processWorkUnit(Scanner.java:473)
	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner$6.processWorkUnit(Scanner.java:467)
	at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue.runWorkLoop(WorkQueue.java:187)
```

Steps to Reproduce
==============================

Please include a numbered list of steps that other people can use to recreate the "Actual Behavior."

1. Create a jenkinsfile 
```
pipeline {
    agent none
    stages {
        stage('test parameters') {
            steps {
                sh 'echo "hello"'
            }
        }
    }
}
```

2. Create a test loading this file
```
import com.homeaway.devtools.jenkins.testing.JenkinsPipelineSpecification

class CheckParameterTest extends JenkinsPipelineSpecification  {

    def "test" () {
        setup:
            def jenkinsFile = loadPipelineScriptForTest("test/pipelines/checkParametersTest.jenkins")
        when:
            jenkinsFile.run()
        then:
            1 * getPipelineMock("node")("hello", _)
    }
}

```

3. Launch a gradlew clean test

Additional Information
==============================

My build.gradle.  :

```
group 'com.talend.jenkins.maintenance.sharedLib'
version 'O.1-SNAPSHOT'

allprojects {
    apply plugin: 'groovy'
    sourceCompatibility = 1.9
    targetCompatibility = 1.9
}

buildscript {
    repositories {
        mavenCentral()
    }
}

repositories {
    mavenCentral()
    maven {
      url "https://repo.jenkins-ci.org/releases/"
    }
    maven {
      url "https://repo.jenkins-ci.org/public/"
    }
}

dependencies {
    compile group: 'com.cloudbees', name: 'groovy-cps', version: '1.24'
    compile group: 'org.codehaus.groovy', name: 'groovy-json', version: '2.5.2'

    testCompile 'com.homeaway.devtools.jenkins:jenkins-spock:2.1.0'
    testCompile(group: 'org.jenkins-ci.plugins.workflow', name: 'workflow-step-api', version:'2.22') {
      artifact {
        name = "workflow-step-api"
        type = 'jar'
      }
    }
    testCompile "org.jenkins-ci:symbol-annotation:1.10"
    testCompile "junit:junit:4.12"
    testCompile "javax.servlet:javax.servlet-api:3.1.0"
    testCompile "org.connectbot.jbcrypt:jbcrypt:1.0.0"
    testCompile "org.jenkins-ci.main:jenkins-core:2.102"
    testCompile "io.github.lukehutch:fast-classpath-scanner:3.1.6"
}

sourceSets {
    main {
        groovy {
            srcDirs = ['src', 'vars']
        }
    }
    test {
        groovy {
            srcDirs = ['test']
        }
    }
}
```

**Comment by sebarre-talend** [comment]
Note that i have the same error with 2.0.1 version, so maybe this is a dependency error ?

**Comment by awittha** [comment]
This sounds like a Java9+ issue. The classpath scanner doesn't seem to support Java9 bytecode.

A quick search turned up this issue: https://github.com/classgraph/classgraph/issues/141 (the fastclasspathscanner project became classgraph)

~However, it looks like only the `2.6.0-BETA2` release of `classgraph` includes this fix ( https://github.com/microsoft/ApplicationInsights-Java/pull/1173 -> https://github.com/microsoft/ApplicationInsights-Java/pull/1173/commits/0734d4dfcf82fdb7ddc74126366c94dcc6247d99 )~

That's not a huge problem, though, because it looks like Jenkins itself doesn't support Java 9:

> **Java Requirements**
> * Java 8 runtime environments, both 32-bit and 64-bit versions are supported
> * Since Jenkins 2.164 and 2.164.1 [1], Java 11 runtime environments are supported
> ...
> * Java 9 and Java 10 are not supported
> * Java 12 is not supported
> -- https://jenkins.io/doc/administration/requirements/java/

Looking at the error, I expect Java 11 won't work with the classpath scanner, either. Please try running the tests with Java8 and let me know if that works.

**Comment by awittha** [comment]
Oops! I didn't realize GitHub issues would show references across repos, so I mistook a different project's release for this fix as being classgraph's own fix; classgraph may have a release that fixes this.

_However_ Jenkins still doesn't seem to support java9, so just try running the tests with Java8 for now.

**Comment by awittha** [comment]
I pushed a branch of `jenkins-spock` that updates to the latest `classgraph` and doesn't fail any of its unit tests; you could try building it and using it in your project: https://github.com/ExpediaGroup/jenkins-spock/tree/classgraph-upgrade

However - Jenkins itself doesn't seem to support Java9+, so I think running the tests with  Java8 is a far better answer.

**Comment by awittha** [comment]
It _may_ be that you've got some dependencies that were compiled against Java9+, in which case this problem might not be able to be resolved without an update to jenkins-spock. If running the tests with Java8 doesn't fix it, try the updated branch above and let me know if _that_ does.

**Comment by sebarre-talend** [comment]
Hello, and thanks for the time you spent on this issue.
I already was in java8 when the issue occured.
I restarted a new project yesterday, but with maven instead of gradle, and inspired by the pom.xml of your examples in the repo, and the project compiles perfectly this time, so i guess the issue was on my side.
Thanks for your time, i have another question on the use of your lib but this should be on another thread.

Thanks.
