### ISSUE TITLE
java.lang.NoClassDefFoundError when using this library in conjunction with the Jenkins Pipeline Shared Library Groovy Plugin

### ISSUE THREAD

**Issue by wheelerlaw** [ExpediaGroup/jenkins-spock#89]
Expected Behavior
==============================
I am trying to execute the following spec:

```
package hello

import com.homeaway.devtools.jenkins.testing.JenkinsPipelineSpecification

class TestSpec extends JenkinsPipelineSpecification {

    def utils = null

    def setup() {
        utils = loadPipelineScriptForTest("../../../src/hello/Utils.groovy")
    }

    def "a sample test" () {
        given:
        Utils mockedUtils = GroovyMock(global: true)
        mockUtils.mockedMethod("hello") >> "world"

        when:
        utils.testMethod("hello")

        then:
        1 * mockUtils.mockedMethod("")

    }
}
```

Actual Behavior
==============================

I am receiving the following exception when I run my test:

```
org/jboss/modules/ModuleClassLoader
java.lang.NoClassDefFoundError: org/jboss/modules/ModuleClassLoader
	at java.base/java.lang.Class.forName(Class.java:340)
	at com.homeaway.devtools.jenkins.testing.LocalProjectPipelineExtensionDetector.getClassesOfTypeInPackage(LocalProjectPipelineExtensionDetector.java:88)
	at com.homeaway.devtools.jenkins.testing.JenkinsPipelineSpecification.setupSpec(JenkinsPipelineSpecification.groovy:1018)
Caused by: java.lang.ClassNotFoundException: org.jboss.modules.ModuleClassLoader
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 3 more
```

Steps to Reproduce
==============================

Please include a numbered list of steps that other people can use to recreate the "Actual Behavior."

1. Open the included sample project and open it in IntelliJ
2. Within intellij, execute the test by click on the green arrow next to the dest definition. 

Additional Information
==============================

I am using this library in conjunction with [this](https://github.com/mkobit/jenkins-pipeline-shared-libraries-gradle-plugin/blob/master/README.adoc) Gradle plugin, since the plugin does a whole lot of boiler plate stuff to enable Jenkins shared library stuff to compile locally. 

I have a very simple `build.gradle` file:

```
plugins {
    id "com.mkobit.jenkins.pipelines.shared-library" version "0.10.1"
    id 'groovy'
}

repositories {
    jcenter()
    mavenCentral()
    maven { url 'https://repo.jenkins-ci.org/releases/' }
}

dependencies {
    implementation 'org.codehaus.groovy:groovy-all:2.4.15'

    testImplementation 'com.homeaway.devtools.jenkins:jenkins-spock:2.1.2'
    testImplementation "org.spockframework:spock-core:1.2-groovy-2.4"
}

configurations.all {
    exclude group: "com.ibm.icu"
}
```

It seems that the issue only happens when I run the test from within IntelliJ (when I run them from `gradlew build` I don't get the same exception), so I am also going to open a ticket with the JetBrains team to see what's going on.

**Comment by wheelerlaw** [comment]
So I traced the source of the exception to this block of code in the `LocalProjectPipelineExtensionDetectore.java` file:

```java
			try {
				clazz = Class.forName( classname );
			} catch( ClassNotFoundException e ) {
				failures.put( classname, e );
				continue;
			}

```

The value for `classname` is `org.jboss.marshalling.ModularClassResolver$2` when it throws the exception.

**Comment by wheelerlaw** [comment]
I noticed the stack trace did not line up with the methods, since I ended up digging into the source of JDK, and thought something seemed funny. I changed the project SDK version in IntelliJ from 14 to 1.8 and it worked fine. I guess IntelliJ is shipping with JDK 14 nowadays.

**Comment by wheelerlaw** [comment]
I am reopening this issue since it looks like there is a compatibility issue with newer versions of Java. If I run `./gradlew test` with Java 8, there are no issues. However if I run the same command with Java 11, I get that `NoClassDefFoundError` exception. It looks like there was a change in the JDK that wrapped the `ClassNotFoundException` with a `NoClassDefFoundError`. Not sure why. But line 89 of LocalProjectPipelineExtensionDetector.java isn't catching the exception:
